/**
 * Generate the tool inventory FROM CODE.
 *
 * Outputs two artifacts, both committed:
 *   - docs/tools.json   (machine-readable; consumed by scripts/verify-tools.mjs)
 *   - README.md         (human-readable; the table between <!-- TOOLS:START/END -->)
 *
 * Modes:
 *   tsx scripts/gen-tool-docs.mts            → write both artifacts
 *   tsx scripts/gen-tool-docs.mts --check    → regenerate IN MEMORY and exit
 *                                              non-zero if the working tree
 *                                              disagrees. Used by `pnpm docs:check`.
 *
 * WHY this script exists: the hand-maintained EXPECTED_TOOLS list in
 * verify-tools.mjs and the README's "tools" table both drifted from the real
 * registration code. By DERIVING both from the live registrar (calling it
 * against a recorder), the README and verify list cannot disagree with the
 * code — when you add a tool, you regenerate and commit.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import type { McpServer } from "../features/pilot-tools/shared";
import { registerWorkspaceProfileTools } from "../features/workspace-profile/mcp/register";
import { registerPilotMcpTools } from "../features/pilot-tools/mcp/register";
import { operationCount } from "../features/pilot-tools/mcp/client-cap";

type ToolEntry = {
  name: string;
  title?: string;
  description?: string;
  /** Operations this registration carries — >1 for an already-grouped tool. */
  operations?: number;
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, "..");
const README_PATH = resolve(ROOT, "README.md");
const TOOLS_JSON_PATH = resolve(ROOT, "docs/tools.json");

const START_MARKER = "<!-- TOOLS:START -->";
const END_MARKER = "<!-- TOOLS:END -->";

/**
 * Run every register* function against a recorder McpServer that just captures
 * the (name, title, description) of each registration. Does not call any
 * handler, so no network/upstream contact happens.
 */
function collectToolInventory(): ToolEntry[] {
  // Pin to FLAT mode for the canonical inventory, and pin it EXPLICITLY.
  // `delete process.env.GROUPED_TOOLS` used to mean flat; since grouping
  // became the default it means grouped, which would silently reduce this
  // inventory from every operation the server can perform to the ~25 domain
  // tools that carry them. tools.json is the operation inventory — one row per
  // callable operation — so it must be generated flat regardless of the
  // deployed default. The grouped catalog is documented in README/ADR-003 and
  // measured by `pnpm catalog:measure`.
  process.env.GROUPED_TOOLS = "false";
  process.env.ENABLE_ADMIN_TOOLS = "true";
  process.env.ENABLE_WEBHOOK_SIMULATORS = "true";

  const entries: ToolEntry[] = [];
  const recorder: McpServer = {
    registerTool(name, config) {
      entries.push({
        name,
        title: config.title as string | undefined,
        description: config.description as string | undefined,
        operations: operationCount(config.inputSchema),
      });
    },
  };

  registerWorkspaceProfileTools(recorder);
  registerPilotMcpTools(recorder);
  return entries.sort((a, b) => a.name.localeCompare(b.name));
}

/** One-line summary for the README table cell — first line of description, or title. */
function summary(t: ToolEntry): string {
  const desc = t.description?.split("\n")[0]?.trim();
  if (desc && desc.length > 0) return desc;
  return t.title?.trim() ?? "";
}

/** Escape pipe characters so they don't break a Markdown table row. */
function mdCell(text: string): string {
  return text.replace(/\|/g, "\\|");
}

function buildToolsTable(tools: ToolEntry[]): string {
  const lines: string[] = [];
  lines.push(`_Generated by \`pnpm docs:tools\` — do not edit by hand._`);
  lines.push("");
  // Registrations and operations are different numbers: `meetings` and `tasks`
  // are single registrations carrying five actions each, so a bare count of
  // rows understates what the server can do. Say both.
  const operations = tools.reduce((total, t) => total + (t.operations ?? 1), 0);
  lines.push(
    operations === tools.length
      ? `**${tools.length} tools registered.**`
      : `**${tools.length} tools registered, carrying ${operations} operations** ` +
        `(some rows are grouped tools with several actions). Under the default ` +
        `grouped configuration these are exposed as ~25 domain tools — the ` +
        `operation count is the same either way.`,
  );
  lines.push("");
  lines.push("| Tool | Purpose |");
  lines.push("|------|---------|");
  for (const t of tools) {
    lines.push(`| \`${t.name}\` | ${mdCell(summary(t))} |`);
  }
  return lines.join("\n");
}

function applyTableToReadme(readme: string, table: string): string {
  const block = `${START_MARKER}\n${table}\n${END_MARKER}`;
  const re = new RegExp(`${START_MARKER}[\\s\\S]*?${END_MARKER}`);
  if (!re.test(readme)) {
    throw new Error(
      `README markers not found. Add a region delimited by ${START_MARKER} ` +
        `and ${END_MARKER} where the tool table should live.`,
    );
  }
  return readme.replace(re, block);
}

function writeArtifacts(tools: ToolEntry[]): void {
  mkdirSync(dirname(TOOLS_JSON_PATH), { recursive: true });
  writeFileSync(TOOLS_JSON_PATH, JSON.stringify(tools, null, 2) + "\n");

  const readme = readFileSync(README_PATH, "utf8");
  const next = applyTableToReadme(readme, buildToolsTable(tools));
  writeFileSync(README_PATH, next);

  console.log(`✓ Wrote ${tools.length} tools to docs/tools.json`);
  console.log(`✓ Updated README tool table`);
}

function checkArtifacts(tools: ToolEntry[]): never {
  const expectedJson = JSON.stringify(tools, null, 2) + "\n";
  let actualJson = "";
  try {
    actualJson = readFileSync(TOOLS_JSON_PATH, "utf8");
  } catch {
    console.error(`✗ docs/tools.json is missing. Run: pnpm docs:tools`);
    process.exit(1);
  }
  if (actualJson !== expectedJson) {
    console.error(`✗ docs/tools.json is out of date. Run: pnpm docs:tools`);
    process.exit(1);
  }

  const readme = readFileSync(README_PATH, "utf8");
  const expectedReadme = applyTableToReadme(readme, buildToolsTable(tools));
  if (readme !== expectedReadme) {
    console.error(`✗ README tool table is out of date. Run: pnpm docs:tools`);
    process.exit(1);
  }

  console.log(`✓ Tool inventory is up to date (${tools.length} tools)`);
  process.exit(0);
}

const tools = collectToolInventory();
if (process.argv.includes("--check")) {
  checkArtifacts(tools);
} else {
  writeArtifacts(tools);
}
